### ISSUE TITLE
Fails to build on FreeBSD < 12

### ISSUE THREAD

**Issue by jbeich** [jiixyj/epoll-shim#28]
Regressed by ac44fb458b15 due to missing https://github.com/freebsd/freebsd-src/commit/92bb8c68091634c69ad47f69beb9bdcc990e03c3. From [error log](https://github.com/jiixyj/epoll-shim/files/6180635/libepoll-shim-0.0.20210321.log):
```c
In file included from src/compat_kqueue1.c:3:
/usr/include/sys/event.h:75:2: error: unknown type name 'uintptr_t'
        uintptr_t       ident;          /* identifier for this event */
        ^
/usr/include/sys/event.h:77:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         flags;          /* action flags for kqueue */
        ^
/usr/include/sys/event.h:78:2: error: unknown type name 'u_int'
        u_int           fflags;         /* filter flag value */
        ^
/usr/include/sys/event.h:79:2: error: unknown type name 'intptr_t'
        intptr_t        data;           /* filter data value */
        ^
```

**Comment by jiixyj** [comment]
Thanks for the report! Fixed on `master` and the new `v0.0.20210322` tag :)

**Comment by jiixyj** [comment]
FYI: I've started to tag "releases", to (hopefully) make updating the FreeBSD port a bit easier: https://github.com/jiixyj/epoll-shim/releases

**Comment by jiixyj** [comment]
Ah, I see you're already updating the port to use `DISTVERSION` etc. Nice!
