### ISSUE TITLE
Fails to build on FreeBSD 11.*

### ISSUE THREAD

**Issue by jbeich** [jiixyj/epoll-shim#10]
Regressed by 7fff1fc5ed9b. `-Wimplicit-function-declaration` regressed by db0f2de07bf1 + b3be554abd71.
```c
$ cc --version
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
Target: x86_64-unknown-freebsd11.3
Thread model: posix
InstalledDir: /usr/bin

$ pkg install cmake ninja
$ cmake -GNinja .
$ ninja
[5/14] Building C object test/CMakeFiles/kqueue-state.dir/kqueue-state.c.o
FAILED: test/CMakeFiles/kqueue-state.dir/kqueue-state.c.o
/usr/bin/cc  -Itest/../include -std=gnu99 -MD -MT test/CMakeFiles/kqueue-state.dir/kqueue-state.c.o -MF test/CMakeFiles/kqueue-state.dir/kqueue-state.c.o.d -o test/CMakeFiles/kqueue-state.dir/kqueue-state.c.o   -c test/kqueue-state.c
In file included from test/kqueue-state.c:1:
/usr/include/sys/event.h:75:2: error: unknown type name 'uintptr_t'
        uintptr_t       ident;          /* identifier for this event */
        ^
/usr/include/sys/event.h:77:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         flags;          /* action flags for kqueue */
        ^
/usr/include/sys/event.h:78:2: error: unknown type name 'u_int'
        u_int           fflags;         /* filter flag value */
        ^
/usr/include/sys/event.h:79:2: error: unknown type name 'intptr_t'
        intptr_t        data;           /* filter data value */
        ^
4 errors generated.
[6/14] Building C object test/CMakeFiles/many-timers.dir/many-timers.c.o
FAILED: test/CMakeFiles/many-timers.dir/many-timers.c.o
/usr/bin/cc  -Iinclude -std=gnu99 -MD -MT test/CMakeFiles/many-timers.dir/many-timers.c.o -MF test/CMakeFiles/many-timers.dir/many-timers.c.o.d -o test/CMakeFiles/many-timers.dir/many-timers.c.o   -c test/many-timers.c
In file included from test/many-timers.c:1:
/usr/include/sys/event.h:75:2: error: unknown type name 'uintptr_t'
        uintptr_t       ident;          /* identifier for this event */
        ^
/usr/include/sys/event.h:77:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short         flags;          /* action flags for kqueue */
        ^
/usr/include/sys/event.h:78:2: error: unknown type name 'u_int'
        u_int           fflags;         /* filter flag value */
        ^
/usr/include/sys/event.h:79:2: error: unknown type name 'intptr_t'
        intptr_t        data;           /* filter data value */
        ^
test/many-timers.c:65:3: warning: implicit declaration of function 'timespecsub' is invalid in C99 [-Wimplicit-function-declaration]
                timespecsub(&e, &b, &e);
                ^
test/many-timers.c:88:3: warning: implicit declaration of function 'timespecsub' is invalid in C99 [-Wimplicit-function-declaration]
                timespecsub(&e, &b, &e);
                ^
test/many-timers.c:123:3: warning: implicit declaration of function 'timespecsub' is invalid in C99 [-Wimplicit-function-declaration]
                timespecsub(&e, &b, &e);
                ^
test/many-timers.c:175:3: warning: implicit declaration of function 'timespecsub' is invalid in C99 [-Wimplicit-function-declaration]
                timespecsub(&e, &b, &e);
                ^
test/many-timers.c:215:3: warning: implicit declaration of function 'timespecsub' is invalid in C99 [-Wimplicit-function-declaration]
                timespecsub(&e, &b, &e);
                ^
5 warnings and 4 errors generated.
[8/14] Building C object test/CMakeFiles/epoll-test.dir/epoll-test.c.o
ninja: build stopped: subcommand failed.
```

**Comment by jbeich** [comment]
Regressed by 7fff1fc5ed9b.

**Comment by jiixyj** [comment]
Thanks for the report! I haven't tried to build on 11 for a bit. Should be pretty easy to fix, though. I'll have a look later.

**Comment by jiixyj** [comment]
Should be fixed now by commit 1fe0d0b9ad8dab15da0e85b1619d0ae8f316131e. Thanks again for the report!
