### ISSUE TITLE
Missing include for sigset_t on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [jiixyj/epoll-shim#21]
Regressed by 3cf8debb7206. wlroots examples fail to build due to incomplete includes:
```c
FAILED: examples/c590b3c@@input-method@exe/input-method.c.o
cc -Iexamples/c590b3c@@input-method@exe -Iexamples -I../examples -Iprotocol -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/lib/libffi-3.2.1/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWLR_USE_UNSTABLE -Wundef -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter '-DWLR_REL_SRC_DIR="../"' -Wno-missing-field-initializers -Wno-missing-braces -DLIBINPUT_MAJOR=1 -DLIBINPUT_MINOR=15 -DLIBINPUT_PATCH=5 '-DICONDIR="/usr/local/share/icons"' -MD -MQ 'examples/c590b3c@@input-method@exe/input-method.c.o' -MF 'examples/c590b3c@@input-method@exe/input-method.c.o.d' -o 'examples/c590b3c@@input-method@exe/input-method.c.o' -c ../examples/input-method.c
In file included from ../examples/input-method.c:8:
/usr/local/include/libepoll-shim/sys/epoll.h:70:60: error: unknown type name 'sigset_t'
int epoll_pwait(int, struct epoll_event *, int, int, const sigset_t *);
                                                           ^
1 error generated.
```

Test case:
```c
$ cc a.c $(pkg-config --cflags --libs epoll-shim)
In file included from a.c:2:
/usr/local/include/libepoll-shim/sys/epoll.h:70:60: error: unknown type name 'sigset_t'
int epoll_pwait(int, struct epoll_event *, int, int, const sigset_t *);
                                                           ^
1 error generated.

$ cat a.c
#define _POSIX_C_SOURCE 200809L
#include <sys/epoll.h>
int main() {}
```

**Comment by jbeich** [comment]
Test case:
```c
$ cc a.c $(pkg-config --cflags --libs epoll-shim)
$ cat a.c
#define _POSIX_C_SOURCE 200809L
#include <sys/epoll.h>
int main() {}
```

**Comment by jiixyj** [comment]
Thank you for the report and the reproducer!

I missed that `sigset_t` is only included from `sys/types.h` if `__BSD_VISIBLE` is set. But this isn't set when one uses feature test macros such as `_POSIX_C_SOURCE` like in your example. On FreeBSD we should probably just include `sys/signal.h`, just like on OpenBSD and DragonflyBSD.

I've added your test to the testsuite. Please let me know if there are any more issues!
